config/routes.rb
Myguru::Application.routes.draw do
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy] 

  root :to => 'pages#home'

  match '/about',     :to => 'pages#about'
  match '/resource',  :to => 'pages#resource'
  match '/contact',   :to => 'pages#contact'

  match '/signup',    :to => 'users#new'

  match '/signin',    :to => 'sessions#new'
  match '/signout',   :to => 'sessions#destroy'
  

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor	  :password
  attr_accessible :email, :name, :password, :password_confirmation 

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence 	=> true,
  					:length		=> { :maximum => 50 }


  validates :email, :presence 	=> true,
  					:format   	=> { :with => email_regex },
  					:uniqueness => { :case_sensitive => false }

  validates :password, 	:presence 		=> true,
  						:confirmation 	=> true,
  						:length			=> { :within => 6..40 }

  before_save :encrypt_password

  	def has_password?(submitted_password)
  		encrypted_password == encrypt(submitted_password)
  	end

	class << self
		def authenticate(email, submitted_password)
  			user = find_by_email(email)
        (user && user.has_password?(submitted_password)) ? user : nil
  	end

    def authenticate_with_salt(id, cookie_salt)
        user = find_by_id(id)
        (user && user.salt == cookie_salt) ? user : nil
    end
	end
  	
  private

  	def encrypt_password
  		self.salt = make_salt if new_record?
  		self.encrypted_password = encrypt(password)
  	end

  	def encrypt(string)
  		secure_hash("#{salt}--#{string}")
  	end

  	def make_salt
  		secure_hash("#{Time.now.utc}--#{password}")
  	end

  	def secure_hash(string)
  		Digest::SHA2.hexdigest(string)
  	end
end

# == Schema Information
#
# Table name: users
#
#  id                 :integer(4)      not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean(1)      default(FALSE)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  layout 'slate'
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	@title = "Home"
  end

  def about
  	@title = "About"
  end

  def resource
  	@title = "Resources"
  end

  def contact
  	@title = "Contact"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  	@title = "Sign in"
  end

  def create
  	user = User.authenticate(params[:session][:email],
  						     params[:session][:password])
  	if user.nil?
      
  		flash.now[:error] = "Invalid email/password combination"
  		@title = "Sign in"
  		render 'new'
  	else
  		#Handles successful sigin.
  		sign_in user
  		redirect_back_or user
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update] 
  before_filter :admin_user,   :only => :destroy

  def index
    @users = User.paginate(:page => params[:page])
    @title = "All users"
  end

   def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      sign_in @user
  		redirect_to @user, :flash => {:success => "Welcome to Sai Darbar" } #Handle a sucessfull save
  	else
	  	@title = "Sign up"
  		render 'new'
    end
  end

  def edit
    @title = "Edit user"
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, :flash => {:success => "Profile updated." }
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path, :flash => {:success => "User Deleted." }
  end

private

  def authenticate
    deny_access unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
     user = User.find(params[:id])
     redirect_to(root_path) if !current_user.admin? || current_user?(user)     
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Return a title on a per page basis.
	def title
		base_title = "Fakir Baba"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		current_user = user		
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def current_user?(user)
		user == current_user
	end

	def deny_access
		store_location
        redirect_to signin_path, :notice => "Please sign into access this page."
  	end

  	def store_location
  		session[:return_to] = request.fullpath
  	end

  	def redirect_back_or(default)
  		redirect_to(session[:return_to] || default)
  		clear_return_to
  	end

  	def clear_return_to
  		session[:return_to] = nil
  		
  	end

	private

		def user_from_remember_token
			User.authenticate_with_salt(*remember_token)
		end

		def remember_token
			cookies.signed[:remember_token] || [nil, nil]
		end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, :alt 		=> user.name, 
												:class 		=> 'gravatar',
												:gravatar 	=> options )
		
	end
end

app/views/layouts/_footer.html.erb
<div class ="container theme-showcase">
<footer>
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component pull-right" style="padding-left:50px">
                <medium>
                  © 2015 Rights Reserved Sri Muralidhar Baba  
                </medium>
      </div>
    </div>
  </div>
</footer>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href= "">Fakir Baba</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>

        <% if signed_in? %>
          <li><%= link_to "Members", users_path %></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown">Profile<b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>      
            </ul>
            </li>
          <li><%= link_to "Resources", resource_path %></li>
        <% end %>
        <li><%= link_to "Contact", contact_path %></li>
        <% if signed_in? %> 
          <li><%= link_to "Sign out", signout_path %></li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_quotes.html.erb
<div class="row">
          <div class="col-lg-12">
            <h2 id="type-blockquotes">Sai Vachan</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="bs-component">
              <blockquote>
                <medium>
                  तुम जो भी करते हो, तुम चाहे जहाँ भी हो, हमेशा इस बात को याद रखो: मुझे हमेशा इस बात का ज्ञान रहता है कि तुम क्या कर रहे हो.
                </medium>
                
                <small><cite title="Source Title">साईं बाबा</cite></small>
              </blockquote>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="bs-component">
              <blockquote class="pull-right">
                <medium>
                  मेरी दृष्टि हमेशा उनपर रहती है जो मुझे प्रेम करते हैं.
                </medium>
                <small><cite title="Source Title">साईं बाबा</cite></small>
              </blockquote>
            </div>
          </div>
        </div>
      </div>

app/views/layouts/_styling.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "slate", :media => "all" %>
<%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myguru</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/slate.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= title %> </title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/styling' %>
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class ="container theme-showcase">
    <section>
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %>
        </div>
      <% end %>

      <%= yield %>
    </section>
    </div>
      <%= render 'layouts/footer' %>
      
        <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "slate" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>

</html>

app/views/pages/about.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="page-header">
            <h2 class="text-warning">
                About Baba
            </h2>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="bs-component">
                    <img src="assets/babaamma350.png" >
                    <medium class="text-info text-center">
                        <h5>Sri Sri Sri Muralidhar Baba </h5>
                        <h5>Smt Sarojana Amma</h5>
                    </medium>                
                </div>
            </div>
            <div class="col-lg-8">
                <div class="bs-component">
                    <div class="text-justify" style="padding-left:30px">
                        <medium>Sri Sri Sri Muralidhar Baba was born on 10th May 1942 in the village of Manthani, situated at the banks of river Godavari, Karimnagar district, Telangana State, India. Manthani an ancient center of vedic learning, houses many scholars well versed in the ancient knowledge of the vedas and shastras. Baba was born to pious couple Shri Srirambhatla Sitaramaih and Vatsala Bai. From his childhood Babaji showed inclination towards spirituality and god realization. Baba after his matriculation left to Nasik, Maharastra and spent his considerable amount of life span there. Babaji is married to Smt Sarojana and have a family of 2 sons and 2 daughters. He worked in CPWD and settled in Hyderabad. By the grace of Shri Shirdi Sai Baba and Tuljapur Bhavani Matha, Baba has been serving the needy and downtroden to uplift them to a higher and a better living. People come to Baba with problems and get their solutions.<br/><br/>Kabir said : <em>If all the land were turned to paper and all the seas turned to ink, and all the forests into pens to write with, they would still not suffice to describe the greatness of the guru.</em><br/><br/>The very nature of saint is so elevating that only association with them would uplift the assocaited. Hence saints do appear on this earth to fulfil the vaccum created by the ignorance. Shri Krishna himself speaks about this in Gita. Lord Krishna tells Arjuna that if you want to approach me then approach me through a teacher who himself is self realized and who knows who I am so that he can guide you successfully through this spiritual world and make you one with me. Mere study of books cannot make one a guru. One who has studied the vedas and who has direct knowledge of atman through anubhava can only be enrolled as a guru. A jivanmukta or a liberated sage is the real Guru or spiritual preceptor. He is the satguru. He is identical with brahman or the supreme self. He is a knower of brahman.<br/><br/><br/>
                    </div>
                </div>
            </div>

<div class="row">
            <div class="col-lg-8">
                <div class="bs-component">
                    <div class="text-justify">
                        <medium> Adi Shankaracharya begins his gurustotram or verses to the guru with the following sanskrit sloka <em>
                        <br/><br/> गुरुर्ब्रह्मा गुरुर्विष्णुर्गुरुर्देवो महेश्वरः । <br/> गुरुरेव परं ब्रह्म तस्मै श्रीगुरवे नमः ।। <br/><br/> </em> Possession of siddhis is not the test to declare the greatness of a saint or to prove he has attained self-realization. Satgurus do not exhibit miracles or siddhis. Sometimes they may exhibit them in order to convince the aspirants of the existence of super physical things, give them encouragement, and instill faith in their hearts. A satguru is endowed with countless siddhis. He possesses all divine aisvarya, all the wealth of the Lord. The satguru is brahman himself. He is an ocean of bliss, knowledge and mercy. He is the captain of your soul. He is the fountain of joy. He removes all your troubles, sorrows and obstacles. He shows you the right divine path. He tears your veil of ignorance. He makes you immortal and divine. He transmutes your lower,diabolical nature. He gives you the rope of knowledge and saves you when you are drowning in this ocean of samsara. Do not consider him to be only a man. If you take him as a man, you are a beast. Worship your guru and bow to him with reverence. guru is god. A word from him is a word from god. He need not teach anything. Even his presence or company is elevating, inspiring and stirring. The very company itself is self-illumination. Living in his company is spiritual education. Man can learn only from a man, and hence god teaches through a human body. In your guru, you have your human ideal of perfection. He is the pattern from which you wish to mould yourself. Your mind will readily be convinced that such a great soul is fit to be worshipped and revered.
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="bs-component">
                    <br/><br/><br/><br/>
                    <img src="assets/duttatreya1.png" >
                </div>
            </div>
        </div>
    </div>
  

app/views/pages/contact.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="page-header" style="padding-left:40px">
      <h2 class="text-warning">
        Reach us
      </h2><br/><br/><br/>
          <div class="col-lg-3">
            <div class="bs-component">
              <blockquote><h2> श्रद्धा </h2></blockquote>
            </div>
          </div>
          <div class="col-lg-5">
           <div class="bs-component text-center" style="padding-top:0px">
             <img src="assets/babafear.png" >
           </div>
          </div>
          <div class="col-lg-4">
            <div class="bs-component">
              <blockquote class="pull-right"><h2>सबूरी </h2></blockquote>
            </div>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-12">
            <h2></h2>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="bs-component">
              <div class="well" style="text-align:center">
                mail us to info@muralidharbaba.com
              </div>
            </div>
          </div>
    </div>

app/views/pages/home.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
	<div class="jumbotron">
		<div class="page-header" style="padding-left:40px">
			<h2 class="text-warning">
				Home
			</h2>
		</div>
    <div class="col-lg-6">
      <div class="bs-component">
          <blockquote>
           <h2>help ever</h2>
          </blockquote>
      </div>
    </div>
    <div class="col-lg-6">
        <div class="bs-component">
          <blockquote class="pull-right"><h2>hurt never</h2></blockquote>
        </div>
    </div>
      <!-- </div> -->
    <div class="row">
    	<div class="col-lg-2">
        <div class="bs-component">
           <img src="assets/Logo.png" >
           	<% if signed_in? %> 
        		<% else %>
              <div class="col-sm-6" style="padding-left:50px">
          			<%= link_to "Sign up now !", signup_path ,:class => "btn btn-sm btn-warning"%>
              </div>
        		<% end %>
       	</div>
    	</div>
			<div class="col-lg-10">
        <div class="bs-component" style="padding-left:40px">
        	 <div class="text-justify">
        			<medium>Welcome to the web page of Sri Sri Sri Muralidhar Baba (Fakir Baba). With the divine blessings of Sri Babaji we hope to introduce ourselves and people at large to the divine path of spirituality.
      				</medium><br /><br />
    			 </div>
    				<medium class="text-warning text-center">
    					<h4 id="type-blockquotes">Importance of Guru</h4>
    				</medium>
    				<div class="text-justify">
      					<medium>Karma is the cause of happiness and sorrow. No God can influence what a human being wants, this leads to misery, unlimited sorrow and sadness. We are childern of the universal mother who cannot see the misery of her children, so she wanted the Lord to create some method, which could end the misery of mankind. To this the almighty replied <em> "Any human being, no matter what karma he has done earlier in this or his previous births, once he accepts a guru, surrenders himself totally to him (sharnagati) that person's sin would be forgiven and forgotten and he would be on the path to moksha."</em><br /><br />It is very funny that if someone wants to learn music, he looks for a good music teacher. If someone wants to learn tennis he looks for a good tennis coach, but when it comes to spiritual life it is basic human nature that he thinks he is good enough on his own and does not need a teacher in this field. We see around that everything needs a teacher so how on earth we enter the spiritual world without a teacher. That’s why a spiritual teacher or guru is so important. The scriptures also say that a guru is not only important, but is essential which means that there is no choice, if one wants to head towards self realization, then one has to have a guru and there is no allowance to this rule. Guru is the moksha-dvara. He is the gateway to the transcendental truth-consciousness. But, it is the aspirant that has to enter through it. The guru is a help, but the actual task of practical sadhana falls on the aspirant himself.<br /><br /></medium>
      				</div>
    			</div>
    		</div>
    	</div>
    	<%= render 'layouts/quotes' %>
  </div>

app/views/pages/resource.html.erb
<div class="jumbotron">
    <div class="page-header" style="padding-left:40px">
      <h2 class="text-warning">
        The page is under construction
      </h2>
    </div>
  </div>

app/views/shared/_error_messages.html.erb
<div class="bs-component">
	<div class="panel panel-danger">
		<% if @user.errors.any? %>
			<div class="panel-heading">
			<h2 class="panel-title text-center">Error Signing up<br/></h2>
			</div>
			<div class="panel-body">
    			<p> <%= pluralize(@user.errors.count,"  Error") %>
    			</p>
					<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>
<div class="field">
	<%= f.label 		:name, :class =>"control-label" %>
	<%= f.text_field 	:name, :placeholder => "Name", :class => "form-control", :style => "width:230px" %>
</div>
<div class="field">
	<%= f.label 		:email, :class => "control-label" %>
	<%= f.text_field 	:email, :placeholder => "Email id", :class => "form-control", :style => "width:230px" %>
</div>
<div class="field">
	<%= f.label 			:password, :class => "control-label" %>
	<%= f.password_field 	:password, :placeholder =>"Password", :class => "form-control", :style => "width:230px"%> 	
</div>
<div class="field">
	<%= f.label 			:password_confirmation,"Confirmation", :class => "control-label" %>
	<%= f.password_field 	:password_confirmation, :placeholder =>"Password Again", :class => "form-control", :style => "width:230px"%>
</div>	

app/views/users/edit.html.erb
<div class="jumbotron">
	<h2 class="text-warning"> Edit user </h2>
	<%= form_for(@user) do |f| %>
		<%= render 'fields', :f => f %>
		<div class="actions"> <br />
			<%= f.submit"Update" %>
		</div>
	<% end %>
	<br /><br />
	<div>
		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails" target=_blank>Change your gravatar</a>

	</div>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
	<div class="row">
    	<div class="col-lg-3">
        	<div class="bs-component">
	        	<h2 class="text-warning">Members</h2>
            </div>
        </div>
        <div class="col-lg-8">
        	<div class="bs-component">
            	<%= will_paginate %>
            	<table class="table table-striped table-hover">                
                	<tbody>
                		<% @users.each do |user| %>
                			<tr class="primary users">
                				<td><%= gravatar_for user, :size => 30 %></td>
                		   		<td><%= link_to user.name, user %></td>
                		   		<td><%= user.email %></td>
                		   		<% if current_user.admin? %>
                		   		<td> | </td>
                		   		<td> 
								<%= link_to "Delete", user, :method => :delete, :confirm => "You sure?",
										:title => "Delete #{user.name}" %> </td>

								<% end %>
                   			</tr>
                   		<% end %>
                	</tbody>	
				</table>			
				<%= will_paginate %>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
	<h2 class="text-warning"> Sign up </h2>
		<%= form_for(@user) do |f| %>
		<%= render 'fields', :f => f %>
			<div class="actions"><br />
				<%= f.submit"Sign up" %>
			</div>
		<% end %>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="bs-docs-section">
      <div class="row">
          <div class="col-lg-4">
            <div class="bs-component">
              <h2>
                <strong>
                  <%= gravatar_for @user %>
          <%= @user.name %>
                </strong>
              </h2>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="bs-component">
              <table class="table table-striped table-hover">
                <tbody></br></br></br></br>
                <tr class="warning">
                  <td>Name</td>
                        <td><%= @user.name %></td>
                      </tr>
                      <tr class="warning">
                  <td>Link</td>
                        <td><%= link_to user_path(@user), @user %></td>
                      </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
</div>